#pragma once

#include <GL/glew.h>

namespace ObjectGL
{
	enum class ColorBufferType : GLenum
	{
		NONE = GL_NONE,
		FRONT_LEFT = GL_FRONT_LEFT,
		FRONT_RIGHT = GL_FRONT_RIGHT,
		BACK_LEFT = GL_BACK_LEFT,
		BACK_RIGHT = GL_BACK_RIGHT,
		FRONT = GL_FRONT,
		BACK = GL_BACK,
		LEFT = GL_LEFT,
		RIGHT = GL_RIGHT,
		FRONT_AND_BACK = GL_FRONT_AND_BACK,

		COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
		COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1,
		COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2,
		COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3,
		COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4,
		COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5,
		COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6,
		COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7,
		COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8,
		COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9,
		COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10,
		COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11,
		COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12,
		COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13,
		COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14,
		COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15
	};
}
