#pragma once

#include <GL/glew.h>

namespace ObjectGL
{
	enum class FrameBufferStatusType : GLenum
	{
		UNKNOWN_ERROR = 0U,

		COMPLETE = GL_FRAMEBUFFER_COMPLETE,
		UNDEFINED = GL_FRAMEBUFFER_UNDEFINED,
		INCOMPLETE_ATTACHMENT = GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT,
		INCOMPLETE_MISSING_ATTAC = GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT,
		INCOMPLETE_DRAW_BUFFER = GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER,
		INCOMPLETE_READ_BUFFER = GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER,
		UNSUPPORTED = GL_FRAMEBUFFER_UNSUPPORTED,
		INCOMPLETE_MULTISAMPLE = GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE,
		INCOMPLETE_LAYER_TARGETS = GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS
	};
}
