#pragma once

#include <GL/glew.h>

enum class GLDebugMessageSourceType : GLenum
{
	// Calls to the OpenGL API
	API = GL_DEBUG_SOURCE_API,

	// Calls to a window-system API
	WINDOW_SYSTEM = GL_DEBUG_SOURCE_WINDOW_SYSTEM,

	// A compiler for a shading language
	SHADER_COMPILER = GL_DEBUG_SOURCE_SHADER_COMPILER,

	// An application associated with OpenGL
	THIRD_PARTY = GL_DEBUG_SOURCE_THIRD_PARTY,

	// Generated by the user of this application (See glDebugMessageInsert())
	APPLICATION = GL_DEBUG_SOURCE_APPLICATION,

	// Some source that isn't one of these
	OTHER = GL_DEBUG_SOURCE_OTHER
};
