//? #version 460 core

#ifndef __CONSTANT_HEADER__
#define __CONSTANT_HEADER__

// Vertex Attributes //

const uint
	POSITION_LOCATION		= 0U,
	COLOR_LOCATION			= 1U,
	NORMAL_LOCATION			= 2U,
	TEX_COORD_LOCATION		= 3U;

const uint
	MODEL_MATRIX_LOCATION	= 4U;


// Uniform Block Binding Point

const uint
	BINDING_POINT_MATERIAL				= 0U,
	BINDING_POINT_LIGHT					= 1U,
	BINDING_POINT_CAMERA				= 2U,
	BINDING_POINT_CONVOLUTION			= 3U,
	BINDING_POINT_GAMMA_CORRECTION		= 4U,
	BINDING_POINT_SKYBOX				= 5U,
	BINDING_POINT_ATTACHMENT			= 6U,
	BINDING_POINT_DEPTH_BAKING_2D		= 7U,
	BINDING_POINT_DEPTH_BAKING_CUBEMAP	= 8U
	;


// Material //

const uint
	MATERIAL_TYPE_MONO_COLOR			= 0U,
	MATERIAL_TYPE_PHONG					= 1U,
	MATERIAL_TYPE_SILHOUETTE			= 2U,
	MATERIAL_TYPE_OUTLINING_PHONG		= 3U,
	MATERIAL_TYPE_TRANSPARENT_PHONG		= 4U,
	MATERIAL_TYPE_REFLECTION			= 5U,
	MATERIAL_TYPE_REFLECTION_PHONG		= 6U,
	MATERIAL_TYPE_REFRACTION			= 7U,
	MATERIAL_TYPE_EXPLODING_PHONG		= 8U;

const uint
	MATERIAL_OPTION_FLAG_LIGHTING			= (1 << 0),
	MATERIAL_OPTION_FLAG_AMBIENT_TEXTURE	= (1 << 1),
	MATERIAL_OPTION_FLAG_DIFFUSE_TEXTURE	= (1 << 2),
	MATERIAL_OPTION_FLAG_SPECULAR_TEXTURE	= (1 << 3),
	MATERIAL_OPTION_FLAG_EMISSIVE_TEXTURE	= (1 << 4),
	MATERIAL_OPTION_FLAG_SHININESS_TEXTURE	= (1 << 5),
	MATERIAL_OPTION_FLAG_ALPHA_TEXTURE		= (1 << 6),
	MATERIAL_OPTION_FLAG_NORMAL_TEXTURE		= (1 << 7);

const uint
	MATERIAL_VERTEX_FLAG_POS3					= (1 << 0),
	MATERIAL_VERTEX_FLAG_COLOR4					= (1 << 1),
	MATERIAL_VERTEX_FLAG_NORMAL3				= (1 << 2),
	MATERIAL_VERTEX_FLAG_TEXCOORD2				= (1 << 3);


// Light //

const uint MAX_NUM_LIGHTS = 7U;

const uint
	LIGHT_TYPE_DIRECTIONAL	= 0U,
	LIGHT_TYPE_POINT		= 1U,
	LIGHT_TYPE_SPOT			= 2U;

const uint
	LIGHT_DEPTH_BAKING_TYPE_ORTHO		= 0U,
	LIGHT_DEPTH_BAKING_TYPE_CUBEMAP		= 1U
	;


// Post Process //

const uint MAX_NUM_COLOR_ATTACHMENTS = 8U;


// Convolution //

const uint MAX_KERNEL_SIZE = 7U;


// MSAA //

const uint NUM_SAMPLE_POINTS = 4U;

#endif